# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  paygov_r-app:
    image: paygov_r
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://paygov_r-postgresql:5432/Paygov_R
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://paygov_r-postgresql:5432/Paygov_R
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  paygov_r-postgresql:
    image: postgres:13.5
    # volumes:
    #   - ~/volumes/jhipster/Paygov_R/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Paygov_R
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
